negation ={
    "no": "es",
    "no": "ca",
    "sin": "es",
    "negativo": "es",
    "afebril": "es",
    "afebril": "ca",
    "niega": "es",
    "negativos": "es",
    "ausencia de": "es",
    "negativa": "es",
    "sense": "ca",
    "neg": "es",
    "neg": "ca",
    "negativas": "es",
    "asintomatica": "es",
    "asintomatico": "es",
    "ex": "es",
    "ex": "ca",
    "descarta": "ca",
    "inespecifico": "es",
    "falta de": "es",
    "impide": "es",
    "ex-": "es",
    "ex-": "ca",
    "exfumador": "es",
    "se retira": "es",
    "tampoco": "es",
    "nega": "es",
    "nega": "ca",
    "cede": "es",
    "cede": "ca",
    "descartada": "ca",
    "desaparicion de": "es",
    "inespecificos": "es",
    "inestabilidad": "es",
    "retiro": "es",
    "negativo)": "es",
    "negatividad de": "es",
    "retirar": "es",
    "retirar": "ca",
    "negatiu": "ca",
    "excepto": "es",
    "desorientacion": "es",
    "niegan": "es",
    "incapacidad para": "es",
    "ausencia": "es",
    "imposibilidad de": "es",
    "se desestimo": "es",
    "suspendido": "es",
    "negaitvo": "es",
    "ex fumador": "es",
    "ex fumador": "ca",
    "desorientado": "es",
    "ceden": "es",
    "irregulares": "es",
    "indetectable": "es",
    "indetectable": "ca",
    "negatividad": "es",
    "negatividad": "ca",
    "imposibilidad": "es",
    "imposibilidad": "ca",
    "se suspende": "es",
    "negativa)": "es",
    "negativa)": "ca",
    "ninguno": "es",
    "rechaza": "es",
    "en ninguna": "es",
    "desaparecen": "es",
    "arritmicos": "es",
    "desaparicion del": "es",
    "negatividad del": "es",
    "atipicos": "es",
}

uncertainty = {
    "compatible con": "es",
    "probable": "es",
    "probable": "ca",
    "sospecha de": "es",
    "se orienta": "es",
    "probablemente": "es",
    "posible": "es",
    "posible": "ca",
    "sugestiva de": "es",
    "sugestiva de": "ca",
    "aparentemente": "es",
    "compatibles con": "es",
    "dudosa": "es",
    "valorar": "es",
    "valorar": "ca",
    "sugestivo de": "es",
    "podria": "es",
    "parece": "es",
    "sugestivos de": "es",
    "sugestivas de": "es",
    "aparente": "es",
    "posiblemente": "es",
    "vs": "es",
    "vs": "ca",
    "dudoso": "es",
    "sospechosa de": "es",
    "podrian": "es",
    "probables": "es",
    "probables": "ca",
    "dudosamente": "es",
    "sugiere": "es",
    "no": "es",
    "no": "ca",
    "posibilidad de": "es",
    "sin": "es",
    "sospechosas de": "es",
    "impresiona": "es",
    "impresiona": "ca",
    "desconoce": "es",
    "dudosos": "es",
    "sugiriendo": "es",
    "sospecha": "es",
    "parecen": "es",
    "sin poder descartar": "es",
    "sugieren": "es",
    "puede": "es",
    "impresiona de": "es",
    "impresiona de": "ca",
    "compatible amb": "ca",
    "sin aparentes": "es",
    "sin aparente": "es",
    "orientan": "es",
    "no parece": "es",
    "aparentes": "es",
    "sugieran": "es",
    "ssospechosas de": "es",
    "falsa": "es",
    "falsa": "ca",
    "sin claras": "es",
    "sugestivos con": "es",
    "desconocido": "es",
    "pudieran": "es",
    "orienta como": "es",
    "se orientan": "es",
    "plantea": "es",
    "sin clara": "es",
    "indiquen": "es",
    "atribuida": "es",
    "sugestiva como": "es",
    "se desconoce": "es",
    "poco porque": "es",
    "sospechosos de": "es",
    "interpreta": "es",
    "interpreta": "ca",
    "sospitosa de": "ca",
    "al parecer": "es",
    "no es posible descartar": "es",
    "orienta": "es",
    "orienta": "ca",
    "posibles": "es",
    "posibles": "ca",
    "descartar": "es",
    "descartar": "ca",
    "sugiera de": "es",
    "sospechan de": "es",
    "permite descartar": "es",
    "no permite descartar": "es",
    "compatible": "es",
    "compatible": "ca",
    "indeterminado": "es",
    "no clara": "es",
    "no clara": "ca",
    "clara": "es",
    "clara": "ca",
    "orientan como": "es",
    "dubtos": "ca",
}

allclassifications = {**negation, **uncertainty}